dist: trusty
branches:
  only:
  - master
language: node_js
node_js:
  - "10"
install:
  - echo "skipping installation"

jobs:
  include:
    - stage: test
      script: skip # TODO
    - stage: "Build on gitlab"
      script:
        - git config --global http.sslverify false
        - git remote add mirror https://$GITLAB_USER:$GITLAB_TOKEN@$GITLAB_MIRROR_PATH
        - git push -f mirror master