dist: trusty
branches:
  only:
  - master
env:
  - REGISTRY_URL=registry-1.divante.pl
language: node_js
node_js:
  - "10"
install:
  - echo "skipping install"
services:
  - docker
script:
  - echo "building image..."
  - docker build -t $REGISTRY_URL/shopware-pwa/vsf:$TRAVIS_BUILD_ID .