sudo: required
dist: trusty
language: node_js
node_js:
  - "10"
branches:
  only:
    - master
    - /^greenkeeper.*$/

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

jobs:
  include:
    - stage: Test
      script: 
        - yarn test:coverage
      after_script:
        - cat ./coverage/lcov.info | coveralls