sudo: required
dist: trusty
language: node_js
node_js:
  - "10"
branches:
  only:
    - master
    - /^greenkeeper.*$/

os:
  - linux
  - osx
  - windows

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn

jobs:
  allow_failures:
    - os: windows
  include:
    - stage: Test
      script:
        - yarn test:coverage
      after_script:
        - cat ./coverage/lcov.info | coveralls
