name: 🐞 Bug Report
description: Create a bug report to help us improve
title: "[Bug] "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - Canary (generated by CLI)
        - Latest stable (generated by CLI)
        - Contribution (cloned/forked from GH)
        - Previous versions (write which one)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Which element is affected?
      multiple: true
      options:
        - composables
        - shopware-6-client
        - default-theme
        - theme-base
        - documentation
        - plugins
        - CLI
        - CMS
        - nuxt-module
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: macOS
          - **Node**: 14
          - **Shopware API**: 6.4.4.0
          - **Shopware PWA version**: 1.0.0-RC.1
      value: |
          - OS: 
          - Node: 
          - Shopware API: 
          - Shopware PWA version: 
      render: markdown
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
